---
# This playbook deploys OpenSwan VPN server.

- hosts: vpn_servers_west
  user: root

  vars:
    # Name of the xl2rp gateway
    xl2tpd_gateway_name: RW_Gateway
    # Listenting IP address of xl2tpd
    xl2tpd_listen_addr: $ansible_ssh_host
    # Name of your VPN connection
    connection_name: MY_S2S_VPN
    # IP address of the source host machine
    left_ip_address: $ansible_ssh_host
    # Comma Seperated list
    left_private_subnet: 10.51.50.0/24
    # IP address of the target host machine
    right_ip_address: 23.253.102.237
    # Comma Seperated list
    right_private_subnet: 172.16.51.0/24
  roles:
    - common
    - openswan
    - connection

- hosts: vpn_servers_east
  user: root

  vars:
    # Name of the xl2rp gateway
    xl2tpd_gateway_name: RW_Gateway
    # Listenting IP address of xl2tpd
    xl2tpd_listen_addr: $ansible_ssh_host
    # Name of your VPN connection
    connection_name: MY_S2S_VPN
    # IP address of the source host machine
    left_ip_address: $ansible_ssh_host
    left_private_subnet: 172.16.51.0/24
    # IP address of the target host machine
    right_ip_address: 192.237.172.78
    right_private_subnet: 10.51.50.0/24
  roles:
    - common
    - openswan
    - connection